# Permalinks
permalink:           pretty

# Setup
title:               Baddy Blog
tagline:             Stuff I Actually Care About
url:                 http://Baddy2Shoes.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Lawrence
  url:               
  email:             lawrencewang01@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/Baddy2Shoes

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
